### ISSUE TITLE
Throw err; // Unhandled 'error' event

### ISSUE THREAD

**Issue by nexuspcs** [blynkkk/blynk-library#571]
Here is my output after running a node.js script for about 12 hours:

```
Connecting to TCP: blynk.cloud 80
Connected
Authorized
node:events:518
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('ECONNRESET')
    at new NodeError (node:internal/errors:372:5)
    at Blynk.emit (node:events:516:17)
    at Blynk.error (/home/doorpi/myapp/node_modules/blynk-library/blynk.js:649:8)
    at exports.TcpClient.<anonymous> (/home/doorpi/myapp/node_modules/blynk-library/blynk.js:612:48)
    at exports.TcpClient.emit (node:events:527:28)
    at Socket.<anonymous> (/home/doorpi/myapp/node_modules/blynk-library/blynk-node.js:59:14)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_UNHANDLED_ERROR',
  context: 'ECONNRESET'
}
```
Would be good for some help, I asked before, but nothing...

**Comment by nexuspcs** [comment]
I have also opened here:
https://community.blynk.cc/t/node518-throw-err-unhandled-error-event/62621?u=npcs001

**Comment by nexuspcs** [comment]
any help would be nice....

**Comment by vshymanskyy** [comment]
Unrelated to this library
